name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: ">=2.17.1 <3.1.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^7.6.0
  logger: ^2.0.1
  dio: ^5.3.2
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

